# Generated by Django 4.2 on 2023-04-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0003_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wallpaper'),
        ),
    ]
